<?php

return [
    'auth' => [
        'login' => [
            'title' => ['en' => 'Welcome back', 'ar' => 'مرحبًا بعودتك'],
            'subtitle' => ['en' => 'Sign in with your tenant account to continue.', 'ar' => 'سجّل الدخول بحسابك المرتبط بالمنشأة للمتابعة.'],
            'hint' => ['en' => 'No real login data yet? Register a new workspace first, then come back here.', 'ar' => 'لا توجد بيانات دخول حقيقية بعد؟ أنشئ مساحة عمل جديدة أولًا ثم ارجع لتسجيل الدخول.'],
            'email_or_phone' => ['en' => 'Email or phone', 'ar' => 'البريد الإلكتروني أو رقم الهاتف'],
            'country_code' => ['en' => 'Country code', 'ar' => 'رمز الدولة'],
            'tenant_slug' => ['en' => 'Tenant slug', 'ar' => 'معرّف المنشأة'],
            'password' => ['en' => 'Password', 'ar' => 'كلمة المرور'],
            'submit' => ['en' => 'Sign in', 'ar' => 'تسجيل الدخول'],
            'empty_tenant_hint' => ['en' => 'Optional if your account belongs to only one workspace.', 'ar' => 'اختياري إذا كان حسابك مرتبطًا بمساحة عمل واحدة فقط.'],
        ],
        'register' => [
            'title' => ['en' => 'Create your workspace', 'ar' => 'أنشئ مساحة عملك'],
            'subtitle' => ['en' => 'A guided setup built for real-estate teams.', 'ar' => 'إعداد مرشد ومصمم لفرق العقارات.'],
            'steps' => [
                ['en' => 'Basics', 'ar' => 'الأساسيات'],
                ['en' => 'Contact', 'ar' => 'التواصل'],
                ['en' => 'Workspace', 'ar' => 'المساحة'],
                ['en' => 'Security', 'ar' => 'الأمان'],
            ],
        ],
    ],
    'hero' => [
        'title' => ['en' => 'Find your next property', 'ar' => 'اعثر على عقارك القادم'],
        'subtitle' => ['en' => 'Curated apartments, villas, offices, and investment opportunities for mobile-first browsing.', 'ar' => 'شقق وفلل ومكاتب وفرص استثمارية مختارة لتجربة بحث مخصصة للموبايل.'],
        'search_placeholder' => ['en' => 'Search city, tower, compound, or agent', 'ar' => 'ابحث عن مدينة أو برج أو مجمع أو وسيط'],
    ],
    'banners' => [
        [
            'id' => 'banner-featured-rentals',
            'title' => ['en' => 'Featured Rentals', 'ar' => 'إيجارات مميزة'],
            'subtitle' => ['en' => 'Ready-to-move apartments with verified photos', 'ar' => 'شقق جاهزة للسكن مع صور موثقة'],
            'cta' => ['en' => 'Explore now', 'ar' => 'استكشف الآن'],
            'image' => 'https://picsum.photos/seed/aqarismart-banner-1/1200/640',
            'theme' => 'primary',
        ],
        [
            'id' => 'banner-family-living',
            'title' => ['en' => 'Family Living', 'ar' => 'سكن عائلي'],
            'subtitle' => ['en' => 'Spacious homes in top neighborhoods', 'ar' => 'منازل واسعة في أفضل الأحياء'],
            'cta' => ['en' => 'See homes', 'ar' => 'شاهد المنازل'],
            'image' => 'https://picsum.photos/seed/aqarismart-banner-2/1200/640',
            'theme' => 'rose',
        ],
        [
            'id' => 'banner-investment',
            'title' => ['en' => 'Investment Picks', 'ar' => 'فرص استثمارية'],
            'subtitle' => ['en' => 'High-demand assets with strong occupancy potential', 'ar' => 'أصول عالية الطلب مع فرص إشغال قوية'],
            'cta' => ['en' => 'View deals', 'ar' => 'عرض الفرص'],
            'image' => 'https://picsum.photos/seed/aqarismart-banner-3/1200/640',
            'theme' => 'dark',
        ],
    ],
    'quick_actions' => [
        [
            'id' => 'action-buy',
            'label' => ['en' => 'Buy', 'ar' => 'شراء'],
            'value' => 'sale',
            'icon' => 'home',
        ],
        [
            'id' => 'action-rent',
            'label' => ['en' => 'Rent', 'ar' => 'إيجار'],
            'value' => 'rent',
            'icon' => 'key',
        ],
        [
            'id' => 'action-compounds',
            'label' => ['en' => 'Compounds', 'ar' => 'مجمعات'],
            'value' => 'compound',
            'icon' => 'building',
        ],
        [
            'id' => 'action-invest',
            'label' => ['en' => 'Invest', 'ar' => 'استثمار'],
            'value' => 'investment',
            'icon' => 'chart',
        ],
    ],
    'categories' => [
        [
            'id' => 1,
            'slug' => 'apartments',
            'name' => ['en' => 'Apartments', 'ar' => 'شقق'],
            'image' => 'https://picsum.photos/seed/aqarismart-category-apartments/480/320',
            'count' => 148,
        ],
        [
            'id' => 2,
            'slug' => 'villas',
            'name' => ['en' => 'Villas', 'ar' => 'فلل'],
            'image' => 'https://picsum.photos/seed/aqarismart-category-villas/480/320',
            'count' => 36,
        ],
        [
            'id' => 3,
            'slug' => 'offices',
            'name' => ['en' => 'Offices', 'ar' => 'مكاتب'],
            'image' => 'https://picsum.photos/seed/aqarismart-category-offices/480/320',
            'count' => 22,
        ],
        [
            'id' => 4,
            'slug' => 'lands',
            'name' => ['en' => 'Lands', 'ar' => 'أراضٍ'],
            'image' => 'https://picsum.photos/seed/aqarismart-category-lands/480/320',
            'count' => 18,
        ],
    ],
    'cities' => [
        [
            'id' => 1,
            'name_en' => 'Amman',
            'name_ar' => 'عمّان',
            'image' => 'https://picsum.photos/seed/aqarismart-city-amman/640/420',
            'units_count' => 74,
        ],
        [
            'id' => 2,
            'name_en' => 'Riyadh',
            'name_ar' => 'الرياض',
            'image' => 'https://picsum.photos/seed/aqarismart-city-riyadh/640/420',
            'units_count' => 43,
        ],
        [
            'id' => 3,
            'name_en' => 'Jeddah',
            'name_ar' => 'جدة',
            'image' => 'https://picsum.photos/seed/aqarismart-city-jeddah/640/420',
            'units_count' => 28,
        ],
        [
            'id' => 4,
            'name_en' => 'Irbid',
            'name_ar' => 'إربد',
            'image' => 'https://picsum.photos/seed/aqarismart-city-irbid/640/420',
            'units_count' => 19,
        ],
    ],
    'services' => [
        [
            'id' => 'service-verified',
            'title' => ['en' => 'Verified listings', 'ar' => 'إعلانات موثقة'],
            'description' => ['en' => 'Every listing includes cleaned mobile-ready details and placeholder media.', 'ar' => 'كل إعلان يحتوي على تفاصيل مهيأة للموبايل ووسائط تجريبية.'],
            'icon' => 'shield',
        ],
        [
            'id' => 'service-tours',
            'title' => ['en' => 'Virtual tours', 'ar' => 'جولات افتراضية'],
            'description' => ['en' => 'Highlight units that can later connect to video walkthroughs or reels.', 'ar' => 'إبراز الوحدات التي يمكن ربطها لاحقًا بجولات فيديو أو ريلز.'],
            'icon' => 'play',
        ],
        [
            'id' => 'service-neighborhoods',
            'title' => ['en' => 'Neighborhood insights', 'ar' => 'معلومات الأحياء'],
            'description' => ['en' => 'Use city and tenant sections to build discovery blocks on mobile.', 'ar' => 'استخدم أقسام المدن والمنشآت لبناء وحدات اكتشاف على الموبايل.'],
            'icon' => 'map',
        ],
    ],
    'tenants' => [
        [
            'id' => 101,
            'name' => 'Aqari Prime',
            'slug' => 'aqari-prime',
            'plan' => 'enterprise',
            'branding' => [
                'logo_url' => 'https://picsum.photos/seed/aqarismart-tenant-1-logo/160/160',
                'primary_color' => '#C81E4A',
                'accent_color' => '#111827',
            ],
            'summary' => [
                'description' => 'Premium property management and curated residential listings across Amman.',
                'city' => 'Amman',
                'coverage' => 'Abdoun, Dabouq, Sweifieh',
                'address' => 'Abdoun Circle, Amman',
                'phone' => '+962790000001',
                'email' => 'hello@aqariprime.test',
                'website' => 'https://aqariprime.test',
            ],
            'stats' => [
                'units_count' => 42,
                'active_units_count' => 18,
                'agents_count' => 7,
            ],
            'subscription' => [
                'status' => 'active',
                'package_name' => 'Enterprise',
            ],
        ],
        [
            'id' => 102,
            'name' => 'Skyline Estates',
            'slug' => 'skyline-estates',
            'plan' => 'business',
            'branding' => [
                'logo_url' => 'https://picsum.photos/seed/aqarismart-tenant-2-logo/160/160',
                'primary_color' => '#0F766E',
                'accent_color' => '#164E63',
            ],
            'summary' => [
                'description' => 'Modern apartments and serviced homes for families and young professionals.',
                'city' => 'Riyadh',
                'coverage' => 'Al Malqa, Hittin, Al Narjis',
                'address' => 'Northern Ring Road, Riyadh',
                'phone' => '+966500000002',
                'email' => 'team@skyline.test',
                'website' => 'https://skyline.test',
            ],
            'stats' => [
                'units_count' => 31,
                'active_units_count' => 12,
                'agents_count' => 5,
            ],
            'subscription' => [
                'status' => 'active',
                'package_name' => 'Business',
            ],
        ],
        [
            'id' => 103,
            'name' => 'Harbor Living',
            'slug' => 'harbor-living',
            'plan' => 'pro',
            'branding' => [
                'logo_url' => 'https://picsum.photos/seed/aqarismart-tenant-3-logo/160/160',
                'primary_color' => '#1D4ED8',
                'accent_color' => '#1E293B',
            ],
            'summary' => [
                'description' => 'Coastal apartments, family homes, and long-stay furnished units.',
                'city' => 'Jeddah',
                'coverage' => 'Ash Shati, Al Zahra, Al Rawdah',
                'address' => 'Corniche Road, Jeddah',
                'phone' => '+966500000003',
                'email' => 'hello@harbor.test',
                'website' => 'https://harbor.test',
            ],
            'stats' => [
                'units_count' => 24,
                'active_units_count' => 9,
                'agents_count' => 4,
            ],
            'subscription' => [
                'status' => 'active',
                'package_name' => 'Pro',
            ],
        ],
    ],
    'featured_units' => [
        [
            'id' => 5001,
            'code' => 'APT-AM-101',
            'tenant_id' => 101,
            'listing_type' => 'rent',
            'translated_title' => 'Modern furnished apartment in Abdoun',
            'translated_description' => '2-bedroom apartment with balcony, concierge, and private parking.',
            'price' => 1200,
            'currency' => 'JOD',
            'bedrooms' => 2,
            'bathrooms' => 2,
            'area_m2' => 132,
            'photos' => [
                'https://picsum.photos/seed/aqarismart-unit-1-1/900/640',
                'https://picsum.photos/seed/aqarismart-unit-1-2/900/640',
                'https://picsum.photos/seed/aqarismart-unit-1-3/900/640',
            ],
            'property' => [
                'name' => 'Abdoun Heights',
                'address' => 'Abdoun, Amman',
            ],
            'city' => [
                'name_en' => 'Amman',
                'name_ar' => 'عمّان',
            ],
            'subcategory' => [
                'name' => 'Apartment',
                'category_name' => 'Residential',
            ],
            'badges' => ['Featured', 'Verified', 'Ready'],
            'agent' => [
                'name' => 'Maya Khalil',
                'phone' => '+962790001001',
            ],
        ],
        [
            'id' => 5002,
            'code' => 'APT-RY-204',
            'tenant_id' => 102,
            'listing_type' => 'sale',
            'translated_title' => 'Family apartment with skyline view',
            'translated_description' => 'Large 3-bedroom home near schools, retail, and parks.',
            'price' => 980000,
            'currency' => 'SAR',
            'bedrooms' => 3,
            'bathrooms' => 3,
            'area_m2' => 188,
            'photos' => [
                'https://picsum.photos/seed/aqarismart-unit-2-1/900/640',
                'https://picsum.photos/seed/aqarismart-unit-2-2/900/640',
                'https://picsum.photos/seed/aqarismart-unit-2-3/900/640',
            ],
            'property' => [
                'name' => 'Skyline Residences',
                'address' => 'Hittin, Riyadh',
            ],
            'city' => [
                'name_en' => 'Riyadh',
                'name_ar' => 'الرياض',
            ],
            'subcategory' => [
                'name' => 'Apartment',
                'category_name' => 'Residential',
            ],
            'badges' => ['New', 'Mortgage ready'],
            'agent' => [
                'name' => 'Fahad Al Otaibi',
                'phone' => '+966500010204',
            ],
        ],
        [
            'id' => 5003,
            'code' => 'VIL-JD-011',
            'tenant_id' => 103,
            'listing_type' => 'rent',
            'translated_title' => 'Sea-view villa with private garden',
            'translated_description' => 'Luxury villa with 4 bedrooms, pool deck, and direct access roads.',
            'price' => 18500,
            'currency' => 'SAR',
            'bedrooms' => 4,
            'bathrooms' => 5,
            'area_m2' => 420,
            'photos' => [
                'https://picsum.photos/seed/aqarismart-unit-3-1/900/640',
                'https://picsum.photos/seed/aqarismart-unit-3-2/900/640',
                'https://picsum.photos/seed/aqarismart-unit-3-3/900/640',
            ],
            'property' => [
                'name' => 'Harbor Villas',
                'address' => 'Ash Shati, Jeddah',
            ],
            'city' => [
                'name_en' => 'Jeddah',
                'name_ar' => 'جدة',
            ],
            'subcategory' => [
                'name' => 'Villa',
                'category_name' => 'Residential',
            ],
            'badges' => ['Luxury', 'Sea view'],
            'agent' => [
                'name' => 'Yousef Saeed',
                'phone' => '+966500000311',
            ],
        ],
        [
            'id' => 5004,
            'code' => 'OFF-AM-809',
            'tenant_id' => 101,
            'listing_type' => 'rent',
            'translated_title' => 'Fitted office in business district',
            'translated_description' => 'Move-in ready office with meeting room and reception area.',
            'price' => 2400,
            'currency' => 'JOD',
            'bedrooms' => 0,
            'bathrooms' => 1,
            'area_m2' => 146,
            'photos' => [
                'https://picsum.photos/seed/aqarismart-unit-4-1/900/640',
                'https://picsum.photos/seed/aqarismart-unit-4-2/900/640',
                'https://picsum.photos/seed/aqarismart-unit-4-3/900/640',
            ],
            'property' => [
                'name' => 'Prime Offices Tower',
                'address' => 'Shmeisani, Amman',
            ],
            'city' => [
                'name_en' => 'Amman',
                'name_ar' => 'عمّان',
            ],
            'subcategory' => [
                'name' => 'Office',
                'category_name' => 'Commercial / Office',
            ],
            'badges' => ['Commercial', 'Parking'],
            'agent' => [
                'name' => 'Dana Nasser',
                'phone' => '+962790008809',
            ],
        ],
        [
            'id' => 5005,
            'code' => 'APT-IR-305',
            'tenant_id' => 101,
            'listing_type' => 'sale',
            'translated_title' => 'Affordable apartment for first buyers',
            'translated_description' => 'Bright 2-bedroom apartment close to main services and schools.',
            'price' => 69000,
            'currency' => 'JOD',
            'bedrooms' => 2,
            'bathrooms' => 2,
            'area_m2' => 118,
            'photos' => [
                'https://picsum.photos/seed/aqarismart-unit-5-1/900/640',
                'https://picsum.photos/seed/aqarismart-unit-5-2/900/640',
                'https://picsum.photos/seed/aqarismart-unit-5-3/900/640',
            ],
            'property' => [
                'name' => 'Irbid Gardens',
                'address' => 'Irbid Center',
            ],
            'city' => [
                'name_en' => 'Irbid',
                'name_ar' => 'إربد',
            ],
            'subcategory' => [
                'name' => 'Apartment',
                'category_name' => 'Residential',
            ],
            'badges' => ['Popular', 'Best value'],
            'agent' => [
                'name' => 'Ahmad Shannak',
                'phone' => '+962790003305',
            ],
        ],
        [
            'id' => 5006,
            'code' => 'APT-RY-612',
            'tenant_id' => 102,
            'listing_type' => 'rent',
            'translated_title' => 'Serviced apartment for executives',
            'translated_description' => 'High-floor furnished apartment with gym access and housekeeping.',
            'price' => 7600,
            'currency' => 'SAR',
            'bedrooms' => 1,
            'bathrooms' => 2,
            'area_m2' => 96,
            'photos' => [
                'https://picsum.photos/seed/aqarismart-unit-6-1/900/640',
                'https://picsum.photos/seed/aqarismart-unit-6-2/900/640',
                'https://picsum.photos/seed/aqarismart-unit-6-3/900/640',
            ],
            'property' => [
                'name' => 'Executive Suites',
                'address' => 'Al Narjis, Riyadh',
            ],
            'city' => [
                'name_en' => 'Riyadh',
                'name_ar' => 'الرياض',
            ],
            'subcategory' => [
                'name' => 'Furnished Apartment',
                'category_name' => 'Residential',
            ],
            'badges' => ['Furnished', 'Concierge'],
            'agent' => [
                'name' => 'Reem Al Harbi',
                'phone' => '+966500006612',
            ],
        ],
    ],
    'sections' => [
        'featured' => [
            'title' => 'Featured listings',
            'subtitle' => 'Hand-picked properties for the first marketplace section',
            'unit_codes' => ['APT-AM-101', 'APT-RY-204', 'VIL-JD-011'],
        ],
        'recommended' => [
            'title' => 'Recommended for you',
            'subtitle' => 'A mixed feed of apartments, villas, and offices for the main card list',
            'unit_codes' => ['OFF-AM-809', 'APT-IR-305', 'APT-RY-612'],
        ],
        'top_tenants' => [
            'title' => 'Top agencies',
            'subtitle' => 'Trusted agencies and property managers',
            'tenant_slugs' => ['aqari-prime', 'skyline-estates', 'harbor-living'],
        ],
        'popular_cities' => [
            'title' => 'Explore by city',
            'subtitle' => 'Browse high-demand cities and neighborhoods',
            'city_names' => ['Amman', 'Riyadh', 'Jeddah', 'Irbid'],
        ],
    ],
];
